jobs:

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      SYMLINK=5_16_0_0
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

  - template: templates/steps.yml  # Template reference
  - script: |
      msbuild MacTerminal/MacTerminal.csproj

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: templates/steps.yml  # Template reference
