jobs:

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: ls /Library/Frameworks/Mono.framework/Versions/
  - template: templates/steps.yml  # Template reference

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: templates/steps.yml  # Template reference
